LavenderTown_hns_MapScripts::
	.byte 0

LavenderTown_EventScript_Npc1::
	lock
	faceplayer
	msgbox LavenderTown_EventScript_Npc1_Text, MSGBOX_NPC
	release
	end

LavenderTown_EventScript_Npc2::
	lock
	faceplayer
	msgbox LavenderTown_EventScript_Npc2_Text, MSGBOX_NPC
	release
	end

LavenderTown_EventScript_Npc3::
	lock
	faceplayer
	msgbox LavenderTown_EventScript_Npc3_Text, MSGBOX_NPC
	release
	end

LavenderTown_EventScript_Npc4::
	lock
	faceplayer
	msgbox LavenderTown_EventScript_Npc4_Text, MSGBOX_NPC
	release
	end

LavenderTown_EventScript_Sign1::
	msgbox LavenderTown_EventScript_Sign1_Text, MSGBOX_SIGN
	end

LavenderTown_EventScript_Sign2::
	msgbox LavenderTown_EventScript_Sign2_Text, MSGBOX_SIGN
	end

LavenderTown_EventScript_Sign3::
	msgbox LavenderTown_EventScript_Sign3_Text, MSGBOX_SIGN
	end

LavenderTown_EventScript_Sign4::
	msgbox LavenderTown_EventScript_Sign4_Text, MSGBOX_SIGN
	end

LavenderTown_EventScript_Npc1_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

LavenderTown_EventScript_Npc2_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

LavenderTown_EventScript_Npc3_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

LavenderTown_EventScript_Npc4_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

LavenderTown_EventScript_Sign1_Text:
	.string "A sign from the old routes.$"

LavenderTown_EventScript_Sign2_Text:
	.string "A sign from the old routes.$"

LavenderTown_EventScript_Sign3_Text:
	.string "A sign from the old routes.$"

LavenderTown_EventScript_Sign4_Text:
	.string "A sign from the old routes.$"

