NationalPark_Normal_hns_MapScripts::
	.byte 0

NationalPark_Normal_EventScript_Npc1::
	lock
	faceplayer
	msgbox NationalPark_Normal_EventScript_Npc1_Text, MSGBOX_NPC
	release
	end

NationalPark_Normal_EventScript_Npc2::
	lock
	faceplayer
	msgbox NationalPark_Normal_EventScript_Npc2_Text, MSGBOX_NPC
	release
	end

NationalPark_Normal_EventScript_Npc3::
	lock
	faceplayer
	msgbox NationalPark_Normal_EventScript_Npc3_Text, MSGBOX_NPC
	release
	end

NationalPark_Normal_EventScript_Npc4::
	lock
	faceplayer
	msgbox NationalPark_Normal_EventScript_Npc4_Text, MSGBOX_NPC
	release
	end

NationalPark_Normal_EventScript_Npc5::
	lock
	faceplayer
	msgbox NationalPark_Normal_EventScript_Npc5_Text, MSGBOX_NPC
	release
	end

NationalPark_Normal_EventScript_Npc6::
	lock
	faceplayer
	msgbox NationalPark_Normal_EventScript_Npc6_Text, MSGBOX_NPC
	release
	end

NationalPark_Normal_EventScript_Npc7::
	lock
	faceplayer
	msgbox NationalPark_Normal_EventScript_Npc7_Text, MSGBOX_NPC
	release
	end

NationalPark_Normal_EventScript_Npc8::
	lock
	faceplayer
	msgbox NationalPark_Normal_EventScript_Npc8_Text, MSGBOX_NPC
	release
	end

NationalPark_Normal_EventScript_Npc9::
	lock
	faceplayer
	msgbox NationalPark_Normal_EventScript_Npc9_Text, MSGBOX_NPC
	release
	end

NationalPark_Normal_EventScript_Npc10::
	lock
	faceplayer
	msgbox NationalPark_Normal_EventScript_Npc10_Text, MSGBOX_NPC
	release
	end

NationalPark_Normal_EventScript_Npc11::
	lock
	faceplayer
	msgbox NationalPark_Normal_EventScript_Npc11_Text, MSGBOX_NPC
	release
	end

NationalPark_Normal_EventScript_Npc12::
	lock
	faceplayer
	msgbox NationalPark_Normal_EventScript_Npc12_Text, MSGBOX_NPC
	release
	end

NationalPark_Normal_EventScript_Portal5::
	warp MAP_ROUTE36_HNS, 16, 20
	waitstate
	end

NationalPark_Normal_EventScript_Portal6::
	warp MAP_ROUTE36_HNS, 16, 20
	waitstate
	end

NationalPark_Normal_EventScript_Npc1_Text:
	.string "They merged the parks too. The flowerbeds took it personally.$"

NationalPark_Normal_EventScript_Npc2_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

NationalPark_Normal_EventScript_Npc3_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

NationalPark_Normal_EventScript_Npc4_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

NationalPark_Normal_EventScript_Npc5_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

NationalPark_Normal_EventScript_Npc6_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

NationalPark_Normal_EventScript_Npc7_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

NationalPark_Normal_EventScript_Npc8_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

NationalPark_Normal_EventScript_Npc9_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

NationalPark_Normal_EventScript_Npc10_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

NationalPark_Normal_EventScript_Npc11_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

NationalPark_Normal_EventScript_Npc12_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

