EcruteakCity_hns_MapScripts::
	.byte 0

EcruteakCity_EventScript_Npc1::
	lock
	faceplayer
	msgbox EcruteakCity_EventScript_Npc1_Text, MSGBOX_NPC
	release
	end

EcruteakCity_EventScript_Npc2::
	lock
	faceplayer
	msgbox EcruteakCity_EventScript_Npc2_Text, MSGBOX_NPC
	release
	end

EcruteakCity_EventScript_Npc3::
	lock
	faceplayer
	msgbox EcruteakCity_EventScript_Npc3_Text, MSGBOX_NPC
	release
	end

EcruteakCity_EventScript_Npc4::
	lock
	faceplayer
	msgbox EcruteakCity_EventScript_Npc4_Text, MSGBOX_NPC
	release
	end

EcruteakCity_EventScript_Npc5::
	lock
	faceplayer
	msgbox EcruteakCity_EventScript_Npc5_Text, MSGBOX_NPC
	release
	end

EcruteakCity_EventScript_Npc6::
	lock
	faceplayer
	msgbox EcruteakCity_EventScript_Npc6_Text, MSGBOX_NPC
	release
	end

EcruteakCity_EventScript_Npc7::
	lock
	faceplayer
	msgbox EcruteakCity_EventScript_Npc7_Text, MSGBOX_NPC
	release
	end

EcruteakCity_EventScript_Npc1_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

EcruteakCity_EventScript_Npc2_Text:
	.string "The BURNED TOWER remembers the fire. The fire remembers nothing.$"

EcruteakCity_EventScript_Npc3_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

EcruteakCity_EventScript_Npc4_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

EcruteakCity_EventScript_Npc5_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

EcruteakCity_EventScript_Npc6_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

EcruteakCity_EventScript_Npc7_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

