#ifndef GUARD_CONSTANTS_PLASTIC_OX_FLAGS_H
#define GUARD_CONSTANTS_PLASTIC_OX_FLAGS_H

#include "constants/plastic_ox_story.h"

// Plastic Ox alpha flags (emerald build only).
//
// Allocation: the documented-unused general-flag run 0x264-0x2BB in
// constants/flags.h (FLAG_UNUSED_0x264 .. FLAG_UNUSED_0x2BB). Every value
// here MUST stay inside that range: FLAGS_COUNT (= DAILY_FLAGS_END + 1)
// sizes the save-block flag array, so anything at or above it would write
// out of bounds, and the 0x500+ / 0x920+ sub-ranges belong to trainer and
// daily flags.

#define POX_FLAGS_START 0x264

// Story beats, one per completed beat (see plastic_ox/alpha/STORY_TRIGGERS.md).
#define FLAG_POX_STORY_STARTER   (POX_FLAGS_START + 0x00)
#define FLAG_POX_STORY_ILEX      (POX_FLAGS_START + 0x01)
#define FLAG_POX_STORY_MTMOON    (POX_FLAGS_START + 0x02)
#define FLAG_POX_STORY_WEATHER   (POX_FLAGS_START + 0x03)
#define FLAG_POX_STORY_MANSION   (POX_FLAGS_START + 0x04)
#define FLAG_POX_STORY_SILPH     (POX_FLAGS_START + 0x05)
#define FLAG_POX_TRIGGERS_ENABLED (POX_FLAGS_START + 0x06)

// Pallet opening: persistent introduction and retryable supply gift.
#define FLAG_POX_LAB_INTRO (POX_FLAGS_START + 0x07)
#define FLAG_POX_STARTER_SUPPLIES (POX_FLAGS_START + 0x08)
#define FLAG_POX_ELM_TMS (POX_FLAGS_START + 0x09)

// Trigger-build-only NPCs hidden in the walkable build (and re-hidden/removed
// by their story beats in the trigger build).
#define FLAG_POX_HIDE_R29_GUARD         (POX_FLAGS_START + 0x0C) // beat 0: R29 gate guard leaves once starter is chosen
#define FLAG_POX_HIDE_MTMOON_GRUNT_1    (POX_FLAGS_START + 0x0D) // beat 5: Rocket I
#define FLAG_POX_HIDE_MTMOON_GRUNT_2    (POX_FLAGS_START + 0x0E)
#define FLAG_POX_HIDE_MTMOON_SCIENTIST  (POX_FLAGS_START + 0x0F)
#define FLAG_POX_HIDE_LAVENDER_GRUNT_1  (POX_FLAGS_START + 0x10) // beat 12: Rocket II tower floors
#define FLAG_POX_HIDE_LAVENDER_GRUNT_2  (POX_FLAGS_START + 0x11)
#define FLAG_POX_HIDE_SILPH_GRUNT_1     (POX_FLAGS_START + 0x12) // beat 16: Rocket III
#define FLAG_POX_HIDE_SILPH_GRUNT_2     (POX_FLAGS_START + 0x13)
#define FLAG_POX_HIDE_SILPH_GRUNT_3     (POX_FLAGS_START + 0x14)
#define FLAG_POX_HIDE_SILPH_GIOVANNI    (POX_FLAGS_START + 0x15)
#define FLAG_POX_HIDE_SAFFRON_GATE_NPC  (POX_FLAGS_START + 0x16) // retired: reserve ID; northern OU access uses Space Center

// Battle-demo NPCs hidden in the walkable/trigger alpha builds; visible only
// in the PLASTIC_OX_BUILD=battle build (see Makefile, src/new_game.c).
#define FLAG_POX_HIDE_BATTLE_OAK_PALLET  (POX_FLAGS_START + 0x17) // Oak in PalletTown (ADV OU team gift)
#define FLAG_POX_HIDE_BATTLE_OAK_LAB     (POX_FLAGS_START + 0x18) // Oak in Oak's Lab (ADV OU team gift)
#define FLAG_POX_HIDE_BATTLE_LANCE       (POX_FLAGS_START + 0x19) // Lance in OldaleTown (battle trigger)

// Item balls / hidden items for imported maps: allocate sequentially from
// POX_HIDDEN_ITEMS_BASE, one flag per placement (IMPORT_GUIDE section 2).
#define POX_HIDDEN_ITEMS_BASE           (POX_FLAGS_START + 0x1C) // 0x280; run ends at 0x2BB

// Wave 1C (Leg A) item placements.
#define FLAG_POX_HIDDEN_R29_POTION             (POX_HIDDEN_ITEMS_BASE + 0)
#define FLAG_POX_HIDDEN_R30_POTION_1           (POX_HIDDEN_ITEMS_BASE + 1)
#define FLAG_POX_HIDDEN_R30_POTION_2           (POX_HIDDEN_ITEMS_BASE + 2)
#define FLAG_POX_HIDDEN_R31_POKEBALL           (POX_HIDDEN_ITEMS_BASE + 3)
#define FLAG_POX_HIDDEN_R31_ANTIDOTE           (POX_HIDDEN_ITEMS_BASE + 4)
#define FLAG_POX_HIDDEN_R46_REVIVE             (POX_HIDDEN_ITEMS_BASE + 5)
#define FLAG_POX_HIDDEN_DARKCAVE_POTION        (POX_HIDDEN_ITEMS_BASE + 6)
#define FLAG_POX_HIDDEN_DARKCAVE_REVIVE        (POX_HIDDEN_ITEMS_BASE + 7)
#define FLAG_POX_HIDDEN_DARKCAVE_MAXREVIVE     (POX_HIDDEN_ITEMS_BASE + 8)
#define FLAG_POX_HIDDEN_DARKCAVE_ELIXIR        (POX_HIDDEN_ITEMS_BASE + 9)
#define FLAG_POX_HIDDEN_DARKCAVE_MAXETHER      (POX_HIDDEN_ITEMS_BASE + 10)
#define FLAG_POX_HIDDEN_DARKCAVE_BLACKFLUTE    (POX_HIDDEN_ITEMS_BASE + 11)
#define FLAG_POX_HIDDEN_CHERRYGROVE_NUGGET_1   (POX_HIDDEN_ITEMS_BASE + 12)
#define FLAG_POX_HIDDEN_CHERRYGROVE_NUGGET_2   (POX_HIDDEN_ITEMS_BASE + 13)


// Wave 2 (Legs B+C) items/hidden.
#define FLAG_POX_HIDDEN_ILEXFOREST_13            (POX_HIDDEN_ITEMS_BASE + 14)
#define FLAG_POX_HIDDEN_ILEXFOREST_14            (POX_HIDDEN_ITEMS_BASE + 15)
#define FLAG_POX_HIDDEN_ILEXFOREST_15            (POX_HIDDEN_ITEMS_BASE + 16)
#define FLAG_POX_HIDDEN_ILEXFOREST_16            (POX_HIDDEN_ITEMS_BASE + 17)
#define FLAG_POX_HIDDEN_ILEXFOREST_7             (POX_HIDDEN_ITEMS_BASE + 18)
#define FLAG_POX_HIDDEN_ILEXFOREST_8             (POX_HIDDEN_ITEMS_BASE + 19)
#define FLAG_POX_HIDDEN_ILEXFOREST_9             (POX_HIDDEN_ITEMS_BASE + 20)
#define FLAG_POX_HIDDEN_MTMOON_CAVE_21           (POX_HIDDEN_ITEMS_BASE + 21)
#define FLAG_POX_HIDDEN_ROUTE14_23               (POX_HIDDEN_ITEMS_BASE + 22)
#define FLAG_POX_HIDDEN_ROUTE2_1                 (POX_HIDDEN_ITEMS_BASE + 23)
#define FLAG_POX_HIDDEN_ROUTE2_19                (POX_HIDDEN_ITEMS_BASE + 24)
#define FLAG_POX_HIDDEN_ROUTE2_5                 (POX_HIDDEN_ITEMS_BASE + 25)
#define FLAG_POX_HIDDEN_ROUTE34_17               (POX_HIDDEN_ITEMS_BASE + 26)
#define FLAG_POX_HIDDEN_ROUTE34_18               (POX_HIDDEN_ITEMS_BASE + 27)
#define FLAG_POX_HIDDEN_ROUTE3_20                (POX_HIDDEN_ITEMS_BASE + 28)
#define FLAG_POX_HIDDEN_ROUTE4_1                 (POX_HIDDEN_ITEMS_BASE + 29)
#define FLAG_POX_HIDDEN_ROUTE4_22                (POX_HIDDEN_ITEMS_BASE + 30)
#define FLAG_POX_HIDDEN_ROUTE4_5                 (POX_HIDDEN_ITEMS_BASE + 31)

// Wave 3: unique item flags (old definitions aliased wave-2 items).
#define FLAG_POX_HIDDEN_NATIONALPARK_NORMAL_14   (POX_HIDDEN_ITEMS_BASE + 32)
#define FLAG_POX_HIDDEN_ROUTE24_18               (POX_HIDDEN_ITEMS_BASE + 33)
#define FLAG_POX_HIDDEN_ROUTE25_19               (POX_HIDDEN_ITEMS_BASE + 34)
#define FLAG_POX_HIDDEN_ROUTE36_15               (POX_HIDDEN_ITEMS_BASE + 35)
#define FLAG_POX_HIDDEN_ROUTE38_16               (POX_HIDDEN_ITEMS_BASE + 36)
#define FLAG_POX_HIDDEN_ROUTE38_17               (POX_HIDDEN_ITEMS_BASE + 37)

// Wave 2 (Legs B+C) items/hidden.
#define FLAG_POX_HIDDEN_ROUTE6_3                 (POX_HIDDEN_ITEMS_BASE + 38)

// Wave 4 (Legs F+G) items/hidden.
#define FLAG_POX_HIDDEN_ROUTE12_14               (POX_HIDDEN_ITEMS_BASE + 39)
#define FLAG_POX_HIDDEN_ROUTE12_15               (POX_HIDDEN_ITEMS_BASE + 40)
#define FLAG_POX_HIDDEN_ROUTE12_7                (POX_HIDDEN_ITEMS_BASE + 41)
#define FLAG_POX_HIDDEN_ROUTE12_9                (POX_HIDDEN_ITEMS_BASE + 42)
#define FLAG_POX_HIDDEN_ROUTE21_16               (POX_HIDDEN_ITEMS_BASE + 43)
#define FLAG_POX_HIDDEN_ROUTE21_17               (POX_HIDDEN_ITEMS_BASE + 44)
#define FLAG_POX_HIDDEN_ROUTE21_18               (POX_HIDDEN_ITEMS_BASE + 45)
#define FLAG_POX_HIDDEN_V7_46 (POX_HIDDEN_ITEMS_BASE + 46)
#define FLAG_POX_HIDDEN_V7_47 (POX_HIDDEN_ITEMS_BASE + 47)
#define FLAG_POX_HIDDEN_V7_48 (POX_HIDDEN_ITEMS_BASE + 48)
#define FLAG_POX_HIDDEN_V7_49 (POX_HIDDEN_ITEMS_BASE + 49)
#define FLAG_POX_HIDDEN_V7_50 (POX_HIDDEN_ITEMS_BASE + 50)
#define FLAG_POX_HIDDEN_V7_51 (POX_HIDDEN_ITEMS_BASE + 51)
#define FLAG_POX_HIDDEN_V7_52 (POX_HIDDEN_ITEMS_BASE + 52)
#define FLAG_POX_HIDDEN_V7_53 (POX_HIDDEN_ITEMS_BASE + 53)
#define FLAG_POX_HIDDEN_V7_54 (POX_HIDDEN_ITEMS_BASE + 54)
#define FLAG_POX_HIDDEN_V7_55 (POX_HIDDEN_ITEMS_BASE + 55)
#define FLAG_POX_HIDDEN_V7_56 (POX_HIDDEN_ITEMS_BASE + 56)
#define FLAG_POX_HIDDEN_V7_57 (POX_HIDDEN_ITEMS_BASE + 57)
#define FLAG_POX_STOPPED_SEAFOAM_B3F_CURRENT 0x03C
#define FLAG_POX_STOPPED_SEAFOAM_B4F_CURRENT 0x03D
#define FLAG_POX_HIDE_SEAFOAM_1F_BOULDER_1 0x03E
#define FLAG_POX_HIDE_SEAFOAM_1F_BOULDER_2 0x03F
#define FLAG_POX_HIDE_SEAFOAM_B1F_BOULDER_1 0x040
#define FLAG_POX_HIDE_SEAFOAM_B1F_BOULDER_2 0x041
#define FLAG_POX_HIDE_SEAFOAM_B2F_BOULDER_1 0x042
#define FLAG_POX_HIDE_SEAFOAM_B2F_BOULDER_2 0x043
#define FLAG_POX_HIDE_SEAFOAM_B3F_BOULDER_1 0x044
#define FLAG_POX_HIDE_SEAFOAM_B3F_BOULDER_2 0x045
#define FLAG_POX_HIDE_SEAFOAM_B3F_BOULDER_3 0x046
#define FLAG_POX_HIDE_SEAFOAM_B3F_BOULDER_4 0x047
#define FLAG_POX_HIDE_SEAFOAM_B3F_BOULDER_5 0x048
#define FLAG_POX_HIDE_SEAFOAM_B3F_BOULDER_6 0x049
#define FLAG_POX_HIDE_SEAFOAM_B4F_BOULDER_1 0x04A
#define FLAG_POX_HIDE_SEAFOAM_B4F_BOULDER_2 0x04B
#define FLAG_POX_FOUGHT_ARTICUNO 0x04C
#define FLAG_POX_HIDE_ARTICUNO 0x04D
#define FLAG_POX_HIDE_SEAFOAM_ISLANDS_1F_ICE_HEAL 0x04E
#define FLAG_POX_HIDE_SEAFOAM_ISLANDS_B1F_REVIVE 0x04F
#define FLAG_POX_HIDE_SEAFOAM_ISLANDS_B1F_WATER_STONE 0x26E
#define FLAG_POX_HIDE_SEAFOAM_ISLANDS_B2F_BIG_PEARL 0x26F
#define FLAG_POX_HIDE_SEAFOAM_ISLANDS_B4F_ULTRA_BALL 0x27E
#define VAR_POX_SEAFOAM_STATE 0x40FD
#endif // GUARD_CONSTANTS_PLASTIC_OX_FLAGS_H
