#ifndef GUARD_PLASTIC_OX_STORY_CONSTANTS_H
#define GUARD_PLASTIC_OX_STORY_CONSTANTS_H

// Generated from plastic_ox/alpha/story_flags.json; IDs must remain stable.
// Reserved unused general flags. Never allocate trainer/daily flags here.
#define FLAG_POX_STORY_BURNED_TOWER 0x020
#define FLAG_POX_STORY_FUJI 0x021
#define FLAG_POX_STORY_SPACE_CENTER 0x022
#define FLAG_POX_HIDE_STORY_NPCS 0x023
#define FLAG_POX_STORY_CHERRYGROVE 0x024
#define FLAG_POX_MANSION_KEY 0x025
#define FLAG_POX_GIFT_FAMILY 0x026
#define FLAG_POX_KIMONO_VAPOREON 0x027
#define FLAG_POX_KIMONO_JOLTEON 0x028
#define FLAG_POX_KIMONO_FLAREON 0x029
#define FLAG_POX_KIMONO_ESPEON 0x02A
#define FLAG_POX_KIMONO_UMBREON 0x02B
#define FLAG_POX_GIFT_KIMONO 0x02C
#define FLAG_POX_GIFT_COTTAGE 0x02D
#define FLAG_POX_GIFT_FUJI 0x02E
#define FLAG_POX_ARCHIVE_1 0x02F
#define FLAG_POX_ARCHIVE_2 0x030
#define FLAG_POX_ENTEI 0x031
#define FLAG_POX_GIFT_SPACE 0x032
#define FLAG_POX_LEAGUE_WALLACE 0x033
#define FLAG_POX_LEAGUE_STEVEN 0x034
#define FLAG_POX_LEAGUE_LEAGUELANCE 0x035
#define FLAG_POX_LEAGUE_BLUE 0x036
#define FLAG_POX_LEAGUE_BILL 0x037
#define FLAG_POX_HIDE_UNUSED_ACTOR 0x038
#define FLAG_POX_WHIRL_ITEM 0x039
#define FLAG_POX_VICTORY_ROAD 0x03A
#define FLAG_POX_REACHED_FORTREE 0x03B

#endif
