Route2_ViridianForest_NorthEntrance_Frlg_MapScripts::
	.byte 0

Route2_ViridianForest_NorthEntrance_EventScript_Youngster::
	msgbox Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_EventScript_OldMan::
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_EventScript_CooltrainerF::
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_EventScript_Guard::
	msgbox Route2_ViridianForest_NorthEntrance_Text_GuardDirections, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
	.string "I listened for bird calls all\n"
	.string "the way through ILEX FOREST.\p"
	.string "Now I keep turning around when\n"
	.string "someone's shoes squeak!$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
	.string "I used to step over saplings.\n"
	.string "Now I take the long way round.\p"
	.string "A POKéMON can CUT those skinny\n"
	.string "trees. My knees can't!$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
	.string "My partner started evolving\n"
	.string "just as we left the forest.\p"
	.string "I stopped it. I want a little\n"
	.string "more time with it as it is.\p"
	.string "You can cancel an evolution,\n"
	.string "too. There's no need to rush.$"

Route2_ViridianForest_NorthEntrance_Text_GuardDirections::
	.string "The north door opens onto\n"
	.string "ROUTE 2, toward RUSTBORO.\p"
	.string "The south door leads back\n"
	.string "into ILEX FOREST.\p"
	.string "Please leave the carpet clear\n"
	.string "for people coming through.$"
