Gate_GoldenrodCity_Route35_hns_MapScripts::
	.byte 0

Gate_GoldenrodCity_Route35_EventScript_Npc1::
	lock
	faceplayer
	msgbox Gate_GoldenrodCity_Route35_EventScript_Npc1_Text, MSGBOX_NPC
	release
	end

Gate_GoldenrodCity_Route35_EventScript_Npc2::
	lock
	faceplayer
	msgbox Gate_GoldenrodCity_Route35_EventScript_Npc2_Text, MSGBOX_NPC
	release
	end

Gate_GoldenrodCity_Route35_EventScript_Npc3::
	lock
	faceplayer
	msgbox Gate_GoldenrodCity_Route35_EventScript_Npc3_Text, MSGBOX_NPC
	release
	end

Gate_GoldenrodCity_Route35_EventScript_Npc1_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

Gate_GoldenrodCity_Route35_EventScript_Npc2_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

Gate_GoldenrodCity_Route35_EventScript_Npc3_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

