PoxRouteTrainer_Route101::
	trainerbattle_single TRAINER_PLASTIC_OX_ROUTE101, PoxRouteTrainer_Text_Challenge, PoxRouteTrainer_Text_Defeat
	msgbox PoxRouteTrainer_Text_After, MSGBOX_AUTOCLOSE
	end

PoxRouteTrainer_Route103::
	trainerbattle_single TRAINER_PLASTIC_OX_ROUTE103, PoxRouteTrainer_Text_Challenge, PoxRouteTrainer_Text_Defeat
	msgbox PoxRouteTrainer_Text_After, MSGBOX_AUTOCLOSE
	end

PoxRouteTrainer_Route29::
	trainerbattle_single TRAINER_PLASTIC_OX_ROUTE29, PoxRouteTrainer_Text_Challenge, PoxRouteTrainer_Text_Defeat
	msgbox PoxRouteTrainer_Text_After, MSGBOX_AUTOCLOSE
	end

PoxRouteTrainer_Route46::
	trainerbattle_single TRAINER_PLASTIC_OX_ROUTE46, PoxRouteTrainer_Text_Challenge, PoxRouteTrainer_Text_Defeat
	msgbox PoxRouteTrainer_Text_After, MSGBOX_AUTOCLOSE
	end

PoxRouteTrainer_Route1::
	trainerbattle_single TRAINER_PLASTIC_OX_ROUTE1, PoxRouteTrainer_Text_Challenge, PoxRouteTrainer_Text_Defeat
	msgbox PoxRouteTrainer_Text_After, MSGBOX_AUTOCLOSE
	end

PoxRouteTrainer_Route31::
	trainerbattle_single TRAINER_PLASTIC_OX_ROUTE31, PoxRouteTrainer_Text_Challenge, PoxRouteTrainer_Text_Defeat
	msgbox PoxRouteTrainer_Text_After, MSGBOX_AUTOCLOSE
	end

PoxRouteTrainer_Route104::
	trainerbattle_single TRAINER_PLASTIC_OX_ROUTE104, PoxRouteTrainer_Text_Challenge, PoxRouteTrainer_Text_Defeat
	msgbox PoxRouteTrainer_Text_After, MSGBOX_AUTOCLOSE
	end

PoxRouteTrainer_Route24::
	trainerbattle_single TRAINER_PLASTIC_OX_ROUTE24, PoxRouteTrainer_Text_Challenge, PoxRouteTrainer_Text_Defeat
	msgbox PoxRouteTrainer_Text_After, MSGBOX_AUTOCLOSE
	end

PoxRouteTrainer_Route25::
	trainerbattle_single TRAINER_PLASTIC_OX_ROUTE25, PoxRouteTrainer_Text_Challenge, PoxRouteTrainer_Text_Defeat
	msgbox PoxRouteTrainer_Text_After, MSGBOX_AUTOCLOSE
	end

PoxRouteTrainer_Route44::
	trainerbattle_single TRAINER_PLASTIC_OX_ROUTE44, PoxRouteTrainer_Text_Challenge, PoxRouteTrainer_Text_Defeat
	msgbox PoxRouteTrainer_Text_After, MSGBOX_AUTOCLOSE
	end

PoxRouteTrainer_Text_Challenge::
	.string "Let's see what the local POKéMON\ncan do!$"
PoxRouteTrainer_Text_Defeat::
	.string "That was a good route battle!$"
PoxRouteTrainer_Text_After::
	.string "Every member of my team lives\nsomewhere along this route.$"
