Route35_hns_MapScripts::
	.byte 0

Route35_EventScript_Npc1::
	lock
	faceplayer
	msgbox Route35_EventScript_Npc1_Text, MSGBOX_NPC
	release
	end

Route35_EventScript_Npc2::
	lock
	faceplayer
	msgbox Route35_EventScript_Npc2_Text, MSGBOX_NPC
	release
	end

Route35_EventScript_Npc3::
	lock
	faceplayer
	msgbox Route35_EventScript_Npc3_Text, MSGBOX_NPC
	release
	end

Route35_EventScript_Npc4::
	lock
	faceplayer
	msgbox Route35_EventScript_Npc4_Text, MSGBOX_NPC
	release
	end

Route35_EventScript_Npc5::
	lock
	faceplayer
	msgbox Route35_EventScript_Npc5_Text, MSGBOX_NPC
	release
	end

Route35_EventScript_Npc6::
	lock
	faceplayer
	msgbox Route35_EventScript_Npc6_Text, MSGBOX_NPC
	release
	end

Route35_EventScript_Npc7::
	lock
	faceplayer
	msgbox Route35_EventScript_Npc7_Text, MSGBOX_NPC
	release
	end

Route35_EventScript_Npc8::
	lock
	faceplayer
	msgbox Route35_EventScript_Npc8_Text, MSGBOX_NPC
	release
	end

Route35_EventScript_Npc9::
	lock
	faceplayer
	msgbox Route35_EventScript_Npc9_Text, MSGBOX_NPC
	release
	end

Route35_EventScript_Npc10::
	lock
	faceplayer
	msgbox Route35_EventScript_Npc10_Text, MSGBOX_NPC
	release
	end

Route35_EventScript_Npc11::
	lock
	faceplayer
	msgbox Route35_EventScript_Npc11_Text, MSGBOX_NPC
	release
	end

Route35_EventScript_Npc12::
	lock
	faceplayer
	msgbox Route35_EventScript_Npc12_Text, MSGBOX_NPC
	release
	end

Route35_EventScript_Portal0::
	warp MAP_GOLDENROD_CITY_HNS, 34, 7
	waitstate
	end

Route35_EventScript_Portal3::
	warp MAP_GATE_GOLDENROD_CITY_ROUTE35_HNS, 7, 1
	waitstate
	end

Route35_EventScript_Portal4::
	warp MAP_ROUTE36_HNS, 16, 21
	waitstate
	end

Route35_EventScript_Portal8::
	warp MAP_GOLDENROD_CITY_HNS, 34, 7
	waitstate
	end

Route35_EventScript_Npc1_Text:
	.string "The park charges no entry fee. The squirrels work for tips.$"

Route35_EventScript_Npc2_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

Route35_EventScript_Npc3_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

Route35_EventScript_Npc4_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

Route35_EventScript_Npc5_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

Route35_EventScript_Npc6_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

Route35_EventScript_Npc7_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

Route35_EventScript_Npc8_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

Route35_EventScript_Npc9_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

Route35_EventScript_Npc10_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

Route35_EventScript_Npc11_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

Route35_EventScript_Npc12_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

