#ifndef GUARD_tilesets_H
#define GUARD_tilesets_H

extern const u32 gTilesetTiles_General[];
extern const u16 gTilesetPalettes_General[][16];

extern const struct Tileset *const gTilesetPointer_SecretBase;
extern const struct Tileset *const gTilesetPointer_SecretBaseRedCave;

extern const struct Tileset gTileset_Building;
extern const struct Tileset gTileset_BuildingFrlg;
extern const struct Tileset gTileset_BrendansMaysHouse;
extern const struct Tileset gTileset_GenericBuilding1;
extern const struct Tileset gTileset_General;
extern const struct Tileset gTileset_Petalburg;
extern const struct Tileset gTileset_Rustboro;
extern const struct Tileset gTileset_Fallarbor;
extern const struct Tileset gTileset_Mauville;
extern const struct Tileset gTileset_Slateport;
extern const struct Tileset gTileset_Dewford;
extern const struct Tileset gTileset_Lilycove;
extern const struct Tileset gTileset_Mossdeep;
extern const struct Tileset gTileset_Sootopolis;
extern const struct Tileset gTileset_EverGrande;
extern const struct Tileset gTileset_Pacifidlog;
extern const struct Tileset gTileset_PetalburgGym;
extern const struct Tileset gTileset_PokemonCenter;
extern const struct Tileset gTileset_InsideShip;
extern const struct Tileset gTileset_Fallarbor;
extern const struct Tileset gTileset_Shop;
extern const struct Tileset gTileset_Dewford;
extern const struct Tileset gTileset_BattleFrontier;
extern const struct Tileset gTileset_BattleFrontierOutsideWest;
extern const struct Tileset gTileset_BattleFrontierOutsideEast;
extern const struct Tileset gTileset_BattleArena;
extern const struct Tileset gTileset_BattleDome;
extern const struct Tileset gTileset_BattlePalace;
extern const struct Tileset gTileset_Slateport;
extern const struct Tileset gTileset_Mauville;
extern const struct Tileset gTileset_BattleFrontierOutsideWest;
extern const struct Tileset gTileset_BattleTent;
extern const struct Tileset gTileset_TrainerHill;
extern const struct Tileset gTileset_General_Frlg;
extern const struct Tileset gTileset_PalletTown;
extern const struct Tileset gTileset_ViridianCity;
extern const struct Tileset gTileset_PewterCity;
extern const struct Tileset gTileset_SaffronCity;
extern const struct Tileset gTileset_CeruleanCity;
extern const struct Tileset gTileset_LavenderTown;
extern const struct Tileset gTileset_VermilionCity;
extern const struct Tileset gTileset_CeladonCity;
extern const struct Tileset gTileset_FuchsiaCity;
extern const struct Tileset gTileset_CinnabarIsland;
extern const struct Tileset gTileset_SeviiIslands123;
extern const struct Tileset gTileset_SeviiIslands45;
extern const struct Tileset gTileset_SeviiIslands67;
extern const struct Tileset gTileset_DepartmentStore;
extern const struct Tileset gTileset_PokemonCenterFrlg;
extern const struct Tileset gTileset_SilphCo;
extern const struct Tileset gTileset_SSAnne;
extern const struct Tileset gTileset_SeaCottage;
extern const struct Tileset gTileset_TrainerTower;

// Plastic Ox: HnS (Johto/Kanto) tilesets
extern const struct Tileset gTileset_Johto_General_Hns;
extern const struct Tileset gTileset_Kanto_General_Hns;
extern const struct Tileset gTileset_Johto_South_Hns;
extern const struct Tileset gTileset_Johto_Building_Hns;
extern const struct Tileset gTileset_Kanto_Building_Hns;
extern const struct Tileset gTileset_Johto_NorthEast_Hns;
extern const struct Tileset gTileset_NewBarkTown_Hns;
extern const struct Tileset gTileset_CherrygroveCity_Hns;
extern const struct Tileset gTileset_Cave_Default_Hns;
extern const struct Tileset gTileset_IlexForest_Hns;
extern const struct Tileset gTileset_PalletTown_Hns;
extern const struct Tileset gTileset_Kanto_PokemonCenter_Hns;
extern const struct Tileset gTileset_JohtoMart_Hns;
extern const struct Tileset gTileset_KantoMart_Hns;
extern const struct Tileset gTileset_House_Lab_Hns;
extern const struct Tileset gTileset_Cave_MtMoon_Hns;
extern const struct Tileset gTileset_BurnedTower_Hns;
extern const struct Tileset gTileset_NationalPark_Hns;
extern const struct Tileset gTileset_EcruteakCity_Gym_Hns;
extern const struct Tileset gTileset_Cafe_Hns;
extern const struct Tileset gTileset_EcruteakTheater_Hns;
extern const struct Tileset gTileset_SeaCottage_Hns;
extern const struct Tileset gTileset_Cave_Ice_Hns;
extern const struct Tileset gTileset_Cave_DragonsDen_Hns;
extern const struct Tileset gTileset_BlackthornGym_Hns;
extern const struct Tileset gTileset_SilphCo_Hns;
extern const struct Tileset gTileset_SaffronCity_Gym_Hns;
extern const struct Tileset gTileset_WhirlIslands_Hns;
extern const struct Tileset gTileset_IndigoPlateau_Hns;
extern const struct Tileset gTileset_PokemonCenter_White_Hns;
extern const struct Tileset gTileset_SaffronCity_Hns;
extern const struct Tileset gTileset_Goldenrod_Hns;
extern const struct Tileset gTileset_Route38_Farmland_Hns;
extern const struct Tileset gTileset_CeladonCity_Hns;
extern const struct Tileset gTileset_CeruleanCity_Hns;
extern const struct Tileset gTileset_Route40_Hns;
extern const struct Tileset gTileset_Vermilion_Hns;
extern const struct Tileset gTileset_CianwoodCity_Hns;
extern const struct Tileset gTileset_Blackthorn_Hns;
extern const struct Tileset gTileset_Gate_Standard_Hns;
extern const struct Tileset gTileset_ViridianCity_Hns;
extern const struct Tileset gTileset_PewterCity_Hns;
extern const struct Tileset gTileset_Fuchsia_Hns;
extern const struct Tileset gTileset_Ecruteak_City_Hns;
extern const struct Tileset gTileset_Johto_NorthWest_Hns;
extern const struct Tileset gTileset_VioletCity_Hns;

#endif //GUARD_tilesets_H
