Route14_hns_MapScripts::
	.byte 0

Route14_EventScript_Npc1::
	lock
	faceplayer
	msgbox Route14_EventScript_Npc1_Text, MSGBOX_NPC
	release
	end

Route14_EventScript_Npc2::
	lock
	faceplayer
	msgbox Route14_EventScript_Npc2_Text, MSGBOX_NPC
	release
	end

Route14_EventScript_Npc3::
	lock
	faceplayer
	msgbox Route14_EventScript_Npc3_Text, MSGBOX_NPC
	release
	end

Route14_EventScript_Npc4::
	lock
	faceplayer
	msgbox Route14_EventScript_Npc4_Text, MSGBOX_NPC
	release
	end

Route14_EventScript_Npc5::
	lock
	faceplayer
	msgbox Route14_EventScript_Npc5_Text, MSGBOX_NPC
	release
	end

Route14_EventScript_Npc6::
	lock
	faceplayer
	msgbox Route14_EventScript_Npc6_Text, MSGBOX_NPC
	release
	end

Route14_EventScript_Npc7::
	lock
	faceplayer
	msgbox Route14_EventScript_Npc7_Text, MSGBOX_NPC
	release
	end

Route14_EventScript_Npc8::
	lock
	faceplayer
	msgbox Route14_EventScript_Npc8_Text, MSGBOX_NPC
	release
	end

Route14_EventScript_Npc1_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

Route14_EventScript_Npc2_Text:
	.string "South! GOLDENROD. Bright lights, loud\ntrains, trains to nowhere.$"

Route14_EventScript_Npc3_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

Route14_EventScript_Npc4_Text:
	.string "My crew rides coast to coast now.\nTook a week to learn the turns.$"

Route14_EventScript_Npc5_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

Route14_EventScript_Npc6_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

Route14_EventScript_Npc7_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

Route14_EventScript_Npc8_Text:
	.string "Roads keep ending somewhere they\ndidn't used to.$"

