// Generated by plastic_ox/encounter_tables/apply_pu_v1.py; edit its source tables.
static const struct WildPokemon sPoxRoute29HeadbuttDayMons[] = {
    { 3, 5, SPECIES_SLAKOTH },
    { 3, 5, SPECIES_SPEAROW },
    { 3, 5, SPECIES_LEDYBA },
    { 3, 5, SPECIES_NATU },
    { 3, 5, SPECIES_EXEGGCUTE },
    { 3, 5, SPECIES_PARAS },
    { 3, 5, SPECIES_HOOTHOOT },
};
static const u8 sPoxRoute29HeadbuttDayWeights[] = { 25, 15, 15, 15, 10, 10, 10 };
static const struct WildPokemonInfo sPoxRoute29HeadbuttDay = { 20, sPoxRoute29HeadbuttDayMons, sPoxRoute29HeadbuttDayWeights, ARRAY_COUNT(sPoxRoute29HeadbuttDayMons) };
static const struct WildPokemon sPoxRoute29HeadbuttNightMons[] = {
    { 3, 5, SPECIES_SLAKOTH },
    { 3, 5, SPECIES_SPEAROW },
    { 3, 5, SPECIES_SPINARAK },
    { 3, 5, SPECIES_NATU },
    { 3, 5, SPECIES_EXEGGCUTE },
    { 3, 5, SPECIES_PARAS },
    { 3, 5, SPECIES_HOOTHOOT },
};
static const u8 sPoxRoute29HeadbuttNightWeights[] = { 25, 15, 15, 15, 10, 10, 10 };
static const struct WildPokemonInfo sPoxRoute29HeadbuttNight = { 20, sPoxRoute29HeadbuttNightMons, sPoxRoute29HeadbuttNightWeights, ARRAY_COUNT(sPoxRoute29HeadbuttNightMons) };
static const struct WildPokemon sPoxRoute46HeadbuttDayMons[] = {
    { 4, 6, SPECIES_NATU },
    { 4, 6, SPECIES_SPEAROW },
    { 4, 6, SPECIES_HOOTHOOT },
    { 4, 6, SPECIES_SLAKOTH },
    { 4, 6, SPECIES_EXEGGCUTE },
    { 4, 6, SPECIES_PARAS },
};
static const u8 sPoxRoute46HeadbuttDayWeights[] = { 25, 15, 15, 15, 15, 15 };
static const struct WildPokemonInfo sPoxRoute46HeadbuttDay = { 20, sPoxRoute46HeadbuttDayMons, sPoxRoute46HeadbuttDayWeights, ARRAY_COUNT(sPoxRoute46HeadbuttDayMons) };
static const struct WildPokemon sPoxRoute46HeadbuttNightMons[] = {
    { 4, 6, SPECIES_NATU },
    { 4, 6, SPECIES_SPEAROW },
    { 4, 6, SPECIES_HOOTHOOT },
    { 4, 6, SPECIES_SLAKOTH },
    { 4, 6, SPECIES_EXEGGCUTE },
    { 4, 6, SPECIES_PARAS },
};
static const u8 sPoxRoute46HeadbuttNightWeights[] = { 25, 15, 15, 15, 15, 15 };
static const struct WildPokemonInfo sPoxRoute46HeadbuttNight = { 20, sPoxRoute46HeadbuttNightMons, sPoxRoute46HeadbuttNightWeights, ARRAY_COUNT(sPoxRoute46HeadbuttNightMons) };
static const struct WildPokemon sPoxRoute44HeadbuttDayMons[] = {
    { 10, 13, SPECIES_SPEAROW },
    { 10, 13, SPECIES_MEOWTH },
    { 10, 13, SPECIES_NATU },
    { 10, 13, SPECIES_EXEGGCUTE },
    { 10, 13, SPECIES_SLAKOTH },
    { 10, 13, SPECIES_LEDYBA },
};
static const u8 sPoxRoute44HeadbuttDayWeights[] = { 25, 20, 15, 15, 15, 10 };
static const struct WildPokemonInfo sPoxRoute44HeadbuttDay = { 20, sPoxRoute44HeadbuttDayMons, sPoxRoute44HeadbuttDayWeights, ARRAY_COUNT(sPoxRoute44HeadbuttDayMons) };
static const struct WildPokemon sPoxRoute44HeadbuttNightMons[] = {
    { 10, 13, SPECIES_HOOTHOOT },
    { 10, 13, SPECIES_MEOWTH },
    { 10, 13, SPECIES_NATU },
    { 10, 13, SPECIES_EXEGGCUTE },
    { 10, 13, SPECIES_SLAKOTH },
    { 10, 13, SPECIES_SPINARAK },
};
static const u8 sPoxRoute44HeadbuttNightWeights[] = { 25, 20, 15, 15, 15, 10 };
static const struct WildPokemonInfo sPoxRoute44HeadbuttNight = { 20, sPoxRoute44HeadbuttNightMons, sPoxRoute44HeadbuttNightWeights, ARRAY_COUNT(sPoxRoute44HeadbuttNightMons) };
static const struct WildPokemon sPoxRoute33HeadbuttDayMons[] = {
    { 14, 16, SPECIES_AIPOM },
    { 14, 16, SPECIES_SPEAROW },
    { 14, 16, SPECIES_EXEGGCUTE },
    { 14, 16, SPECIES_NATU },
    { 14, 16, SPECIES_SLAKOTH },
    { 14, 16, SPECIES_HOOTHOOT },
};
static const u8 sPoxRoute33HeadbuttDayWeights[] = { 30, 25, 15, 10, 10, 10 };
static const struct WildPokemonInfo sPoxRoute33HeadbuttDay = { 20, sPoxRoute33HeadbuttDayMons, sPoxRoute33HeadbuttDayWeights, ARRAY_COUNT(sPoxRoute33HeadbuttDayMons) };
static const struct WildPokemon sPoxRoute33HeadbuttNightMons[] = {
    { 14, 16, SPECIES_AIPOM },
    { 14, 16, SPECIES_SPEAROW },
    { 14, 16, SPECIES_EXEGGCUTE },
    { 14, 16, SPECIES_NATU },
    { 14, 16, SPECIES_SLAKOTH },
    { 14, 16, SPECIES_HOOTHOOT },
};
static const u8 sPoxRoute33HeadbuttNightWeights[] = { 30, 25, 15, 10, 10, 10 };
static const struct WildPokemonInfo sPoxRoute33HeadbuttNight = { 20, sPoxRoute33HeadbuttNightMons, sPoxRoute33HeadbuttNightWeights, ARRAY_COUNT(sPoxRoute33HeadbuttNightMons) };
static const struct WildPokemon sPoxRoute35HeadbuttDayMons[] = {
    { 16, 18, SPECIES_SPEAROW },
    { 16, 18, SPECIES_EXEGGCUTE },
    { 16, 18, SPECIES_NATU },
    { 16, 18, SPECIES_SUNKERN },
    { 16, 18, SPECIES_VENONAT },
    { 16, 18, SPECIES_HOOTHOOT },
};
static const u8 sPoxRoute35HeadbuttDayWeights[] = { 30, 20, 15, 15, 10, 10 };
static const struct WildPokemonInfo sPoxRoute35HeadbuttDay = { 20, sPoxRoute35HeadbuttDayMons, sPoxRoute35HeadbuttDayWeights, ARRAY_COUNT(sPoxRoute35HeadbuttDayMons) };
static const struct WildPokemon sPoxRoute35HeadbuttNightMons[] = {
    { 16, 18, SPECIES_HOOTHOOT },
    { 16, 18, SPECIES_EXEGGCUTE },
    { 16, 18, SPECIES_NATU },
    { 16, 18, SPECIES_SUNKERN },
    { 16, 18, SPECIES_VENONAT },
    { 16, 18, SPECIES_SPEAROW },
};
static const u8 sPoxRoute35HeadbuttNightWeights[] = { 30, 20, 15, 15, 10, 10 };
static const struct WildPokemonInfo sPoxRoute35HeadbuttNight = { 20, sPoxRoute35HeadbuttNightMons, sPoxRoute35HeadbuttNightWeights, ARRAY_COUNT(sPoxRoute35HeadbuttNightMons) };
static const struct WildPokemon sPoxParkContestDayMons[] = {
    { 17, 20, SPECIES_CATERPIE },
    { 17, 20, SPECIES_WEEDLE },
    { 17, 20, SPECIES_METAPOD },
    { 17, 20, SPECIES_KAKUNA },
    { 17, 20, SPECIES_PARAS },
    { 17, 20, SPECIES_VENONAT },
    { 17, 20, SPECIES_BUTTERFREE },
    { 17, 20, SPECIES_BEEDRILL },
    { 17, 20, SPECIES_VOLBEAT },
    { 17, 20, SPECIES_ILLUMISE },
};
static const u8 sPoxParkContestDayWeights[] = { 20, 20, 10, 10, 10, 10, 5, 5, 5, 5 };
static const struct WildPokemonInfo sPoxParkContestDay = { 20, sPoxParkContestDayMons, sPoxParkContestDayWeights, ARRAY_COUNT(sPoxParkContestDayMons) };
static const struct WildPokemon sPoxParkContestNightMons[] = {
    { 17, 20, SPECIES_CATERPIE },
    { 17, 20, SPECIES_WEEDLE },
    { 17, 20, SPECIES_METAPOD },
    { 17, 20, SPECIES_KAKUNA },
    { 17, 20, SPECIES_PARAS },
    { 17, 20, SPECIES_VENONAT },
    { 17, 20, SPECIES_BUTTERFREE },
    { 17, 20, SPECIES_BEEDRILL },
    { 17, 20, SPECIES_VOLBEAT },
    { 17, 20, SPECIES_ILLUMISE },
};
static const u8 sPoxParkContestNightWeights[] = { 20, 20, 10, 10, 10, 10, 5, 5, 5, 5 };
static const struct WildPokemonInfo sPoxParkContestNight = { 20, sPoxParkContestNightMons, sPoxParkContestNightWeights, ARRAY_COUNT(sPoxParkContestNightMons) };
static const struct WildPokemon sPoxParkHeadbuttDayMons[] = {
    { 17, 19, SPECIES_LEDYBA },
    { 17, 19, SPECIES_EXEGGCUTE },
    { 17, 19, SPECIES_AIPOM },
    { 17, 19, SPECIES_TAILLOW },
    { 17, 19, SPECIES_WURMPLE },
    { 17, 19, SPECIES_SUNKERN },
};
static const u8 sPoxParkHeadbuttDayWeights[] = { 30, 15, 15, 15, 15, 10 };
static const struct WildPokemonInfo sPoxParkHeadbuttDay = { 20, sPoxParkHeadbuttDayMons, sPoxParkHeadbuttDayWeights, ARRAY_COUNT(sPoxParkHeadbuttDayMons) };
static const struct WildPokemon sPoxParkHeadbuttNightMons[] = {
    { 17, 19, SPECIES_SPINARAK },
    { 17, 19, SPECIES_EXEGGCUTE },
    { 17, 19, SPECIES_AIPOM },
    { 17, 19, SPECIES_TAILLOW },
    { 17, 19, SPECIES_WURMPLE },
    { 17, 19, SPECIES_SUNKERN },
};
static const u8 sPoxParkHeadbuttNightWeights[] = { 30, 15, 15, 15, 15, 10 };
static const struct WildPokemonInfo sPoxParkHeadbuttNight = { 20, sPoxParkHeadbuttNightMons, sPoxParkHeadbuttNightWeights, ARRAY_COUNT(sPoxParkHeadbuttNightMons) };
static const struct WildPokemon sPoxRoute36HeadbuttDayMons[] = {
    { 18, 20, SPECIES_NATU },
    { 18, 20, SPECIES_SLAKOTH },
    { 18, 20, SPECIES_EXEGGCUTE },
    { 18, 20, SPECIES_AIPOM },
    { 18, 20, SPECIES_SHUPPET },
    { 18, 20, SPECIES_DUSKULL },
};
static const u8 sPoxRoute36HeadbuttDayWeights[] = { 30, 20, 15, 15, 10, 10 };
static const struct WildPokemonInfo sPoxRoute36HeadbuttDay = { 20, sPoxRoute36HeadbuttDayMons, sPoxRoute36HeadbuttDayWeights, ARRAY_COUNT(sPoxRoute36HeadbuttDayMons) };
static const struct WildPokemon sPoxRoute36HeadbuttNightMons[] = {
    { 18, 20, SPECIES_NATU },
    { 18, 20, SPECIES_SLAKOTH },
    { 18, 20, SPECIES_EXEGGCUTE },
    { 18, 20, SPECIES_AIPOM },
    { 18, 20, SPECIES_SHUPPET },
    { 18, 20, SPECIES_DUSKULL },
};
static const u8 sPoxRoute36HeadbuttNightWeights[] = { 30, 20, 15, 15, 10, 10 };
static const struct WildPokemonInfo sPoxRoute36HeadbuttNight = { 20, sPoxRoute36HeadbuttNightMons, sPoxRoute36HeadbuttNightWeights, ARRAY_COUNT(sPoxRoute36HeadbuttNightMons) };
static const struct WildPokemon sPoxIlexHeadbuttDayMons[] = {
    { 6, 8, SPECIES_LEDYBA },
    { 6, 8, SPECIES_PINECO },
    { 6, 8, SPECIES_EXEGGCUTE },
    { 6, 8, SPECIES_SUNKERN },
    { 6, 8, SPECIES_CATERPIE },
    { 6, 8, SPECIES_WEEDLE },
    { 6, 8, SPECIES_PARAS },
};
static const u8 sPoxIlexHeadbuttDayWeights[] = { 25, 15, 15, 15, 10, 10, 10 };
static const struct WildPokemonInfo sPoxIlexHeadbuttDay = { 20, sPoxIlexHeadbuttDayMons, sPoxIlexHeadbuttDayWeights, ARRAY_COUNT(sPoxIlexHeadbuttDayMons) };
static const struct WildPokemon sPoxIlexHeadbuttNightMons[] = {
    { 6, 8, SPECIES_SPINARAK },
    { 6, 8, SPECIES_PINECO },
    { 6, 8, SPECIES_EXEGGCUTE },
    { 6, 8, SPECIES_SUNKERN },
    { 6, 8, SPECIES_HOOTHOOT },
    { 6, 8, SPECIES_WEEDLE },
    { 6, 8, SPECIES_PARAS },
};
static const u8 sPoxIlexHeadbuttNightWeights[] = { 25, 15, 15, 15, 10, 10, 10 };
static const struct WildPokemonInfo sPoxIlexHeadbuttNight = { 20, sPoxIlexHeadbuttNightMons, sPoxIlexHeadbuttNightWeights, ARRAY_COUNT(sPoxIlexHeadbuttNightMons) };
